@startuml
!include style.puml
skinparam ArrowFontStyle plain

mainframe Execute FindCommand

box Logic LOGIC_COLOR_T1
participant ":FindCommand" as FindCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Datastore" as Datastore MODEL_COLOR
end box

activate FindCommand

'get PersonStore'
FindCommand -> Model : getMutableDatastore()
activate Model
Model --> FindCommand : Datastore
deactivate Model

FindCommand -> Datastore : getPersonStore()
activate Datastore
Datastore --> FindCommand : PersonStore
deactivate Datastore

'getCombinedPredicate'
FindCommand -> FindCommand : getCombinedPredicate()
activate FindCommand
deactivate FindCommand


alt isSearchingVolunteer && isSearchingBefriendee
    FindCommand -> FindCommand : searchAllPersons()
    activate FindCommand #FFBBBB
    deactivate FindCommand


else isSearchingVolunteer
    FindCommand -> FindCommand : searchVolunteerOnly()
    activate FindCommand #b0e396
    deactivate FindCommand

else else
    FindCommand -> FindCommand : searchBefriendeeOnly()
    activate FindCommand #96ace3
    deactivate FindCommand

end

create CommandResult
FindCommand -> CommandResult
activate CommandResult
CommandResult --> FindCommand
deactivate CommandResult

<-- FindCommand : result

@enduml
