@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyDatastore" as ReadOnlyDatastore
Class "<<interface>>\nReadOnlyPersonStore" as ReadOnlyPersonStore
Class "<<interface>>\nReadOnlyLogStore" as ReadOnlyLogStore
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class Datastore
Class ModelManager
Class UserPrefs

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Datastore .up.|> ReadOnlyDatastore
ReadOnlyPersonStore .up.> ReadOnlyDatastore
ReadOnlyLogStore .up.> ReadOnlyDatastore

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyDatastore
ModelManager -left-> "1" Datastore
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ReadOnlyPersonStore -[hidden]right--> Datastore
ReadOnlyLogStore -[hidden]right--> ReadOnlyPersonStore

'ModelManager --> "~* filtered" Person
@enduml
