@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":PairCommandParser" as PairCommandParser LOGIC_COLOR
participant "p:PairCommand" as PairCommand LOGIC_COLOR
end box

[-> LogicManager : execute("pair 1 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("pair 1 1")
activate AddressBookParser

create PairCommandParser
AddressBookParser -> PairCommandParser
activate PairCommandParser
PairCommandParser --> AddressBookParser
deactivate PairCommandParser

AddressBookParser -> PairCommandParser : parse("1 1")
activate PairCommandParser

create PairCommand
PairCommandParser -> PairCommand
activate PairCommand

PairCommand --> PairCommandParser
deactivate PairCommand

PairCommandParser --> AddressBookParser : f
deactivate PairCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.'
PairCommandParser -[hidden]-> AddressBookParser
destroy PairCommandParser

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> PairCommand : execute()
activate PairCommand

ref over PairCommand : Execute PairCommand



PairCommand --> LogicManager : result
deactivate PairCommand
PairCommand -[hidden]-> LogicManager : result
destroy PairCommand

[<--LogicManager
deactivate LogicManager
@enduml
