@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":DatastoreVersionStorage" as DatastoreVersionStorage MODEL_COLOR
end box

[-> Model : canUndo()
activate Model

Model -> DatastoreVersionStorage : canUndo()
activate DatastoreVersionStorage
DatastoreVersionStorage --> Model
[<-- Model

[-> Model : undoChanges()
Model -> DatastoreVersionStorage : executeUndo()
DatastoreVersionStorage --> Model : prevDatastore
deactivate DatastoreVersionStorage

Model -> Model : setDataStore(prevDatastore)

[<-- Model

deactivate Model

@enduml
